movieprojects1/movieapp1/urls.py
from django.urls import path
from .import views
app_name='movieapp1'

urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieprojects1/movieprojects1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp1.urls'))
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieprojects1/movieapp1/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

movieprojects1/movieapp1/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieprojects1/movieapp1/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import MovieForm
from .models import Movie
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieprojects1/templates/add.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" name="name"  class="form-control"  placeholder="Enter Movie Name">
    </div>

    <div class="form-group">
        <input type="text" name="desc"  class="form-control"  placeholder="Enter Movie Desc">
    </div>
     <div class="form-group">
        <input type="text" name="year"  class="form-control"  placeholder="Enter Movie Year">
    </div>
     <div class="custom-file">
      <input type="file" name="img" class="custom-file-input" id="customFile">
      <label class="custom-file-label" for="customFile">Choose file</label>
   </div><br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>

    <a class="btn btn-dark" href="{% url 'movieapp1:index' %}">Back</a>

{% endblock %}

movieprojects1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Online Movie Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link " href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">About</a>
        <a  class="btn btn-success" href="{% url 'movieapp1:add_movie' %}">Add Movies</a>


    </div>
  </div>

    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>


{% block body %}
{% endblock %}
</body>
</html>

movieprojects1/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
   <h4> Are you want to delete this movie??</h4><br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br><br>
<a class="btn btn-dark" href="{% url 'movieapp1:index' %}">Back</a>

{% endblock %}

movieprojects1/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="350" height="350">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
             <h5>{{movie.desc}}</h5>
             <h6>{{movie.year}}</h6>
                <a  class="btn btn-warning" href="{% url 'movieapp1:update' movie.id %}">Update</a>
                <a  class="btn btn-danger" href="{% url 'movieapp1:delete' movie.id %}">Delete</a>
        </div>
    </div>

    <br>
     <a  class="btn btn-dark" href="{% url 'movieapp1:index' %}">Back</a>
</div>


{% endblock %}

movieprojects1/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">

</form>
<br>
<a class="btn btn-dark" href="{% url 'movieapp1:index' %}">Back</a>

{% endblock %}

movieprojects1/templates/index.html
{% extends 'base.html' %}
{% block body %}

  <div class="card-deck">
      {% for i in movie_list %}
    <div class="card">
        <img src="{{i.img.url}}"  class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <p class="card-text">{{i.desc}}.</p>
            <a href="{% url 'movieapp1:detail'  i.id %}" class="btn btn-warning">View Details</a>

       </div>
   </div>
      {% endfor %}
 </div>



{% endblock %}